project:
  type: website

website:
  title: "arturhgq"
  sidebar:
    tools: 
      - icon: github 
    style: "floating"
    border: true
    search: true
    foreground: "#333333"
    contents: 
      - section: "About"
        contents: 
          - index.qmd
      - section: "Sofware"
        contents: 
          - text: "dtools"
            file: http://dtools.arturhgq.com/
          - text: "dna"
            file: http://dna.arturhgq.com/
          - text: "cpf"
            file: http://cpf.arturhgq.com/
          - text: "ead"
          - file: http://ead.arturhgq.com/
    page-footer: "Copyright 2022, Artur Quirino" 
    
format:
  html:
    theme: default
    css: styles.css
    toc: true
    linkcolor: "#666699"
    monobackgroundcolor: "#f2f2f2"

execute:
  freeze: auto

