project:
  title: arturhgq
  type: website
  output-dir: docs

website:
  twitter-card: 
   card-style: summary
   creator: "@arturhgq"
  open-graph: true
  search:
    location: navbar
    type: overlay
  navbar:
    left:
      - href: index.qmd
        text: Home 
      - text: "Blog"
        href: blog.qmd
      - text: "Software"
        menu:
          - text: "ead"
            href: http://ead.arturhgq.com/
          - text: "dtools"
            href: http://dtools.arturhgq.com/
          - text: "dna"
            href: http://dna.arturhgq.com/
          - text: "ggviz"
            href: http://ggviz.arturhgq.com/
          - text: "read365"
            href: http://read365.arturhgq.com/
          - text: "cpf"
            href: http://cpf.arturhgq.com/
          - text: "cnpj"
            href: http://cnpj.arturhgq.com/
      - text: "Research"
        href: "Research"
      - text: "Teaching"
        href: "Teaching"
      - text: "Publications"
        href: "Publications"
      - text: "Data"
        href: data.qmd
    right:
      - icon: twitter
        href: https://twitter.com/arturhgq
      - icon: github
        menu: 
          - text: Source Code
            url: https://github.com/arturhgq/arturhgq
          - text: Repositories
            url: https://github.com/arturhgq?tab=repositories
  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} 2023 by Artur Quirino<br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>


lang: en
format:
  html:
    theme:
      light: [flatly, custom.scss]
    toc: true
    linkcolor: "#666699"
    monobackgroundcolor: "#f2f2f2"

execute:
  freeze: true

comments:
  giscus:
    repo: arturhgq/arturhgq
    


