project:
  type: website

website:
  title: "arturhgq"
  navbar:
    foreground: "#f2f2f2"
    left: 
      - href: index.qmd
        text: About
      - href: http://dtools.arturhgq.com
        text: dtools
      - href: http://dNA.arturhgq.com
        text: dNA
    right: 
      - icon: search  
      - icon: github
        href: https://github.com/arturhgq
        aria-label: GitHub
  search:
    location: navbar
    type: textbox

format:
  html:
    theme: default
    css: styles.css
    toc: true
    linkcolor: "#666699"
    monobackgroundcolor: "#f2f2f2"



