project:
  type: website

website:
  title: "arturhgq"
  navbar:
    left:
      - href: index.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/arturhgq
        aria-label: GitHub
  search:
    location: navbar
    type: textbox

format:
  html:
    theme: default
    css: styles.css
    toc: true



