project:
  type: website

website:
  title: "arturhgq"
  sidebar:
    collapse-level: 1
    #tools: 
      #- icon: github 
    style: "floating"
    border: true
    search: true
    foreground: "#333333"
    contents: 
      - section: "Home"
        contents: 
          - index.qmd
      - section: "Sofware"
        contents: 
          - text: "dtools"
            file: http://dtools.arturhgq.com/
          - text: "dna"
            file: http://dna.arturhgq.com/
          - text: "ggviz"
            file: http://ggviz.arturhgq.com/
          - text: "read365"
            file: http://read365.arturhgq.com/
          - text: "cpf"
            file: http://cpf.arturhgq.com/
          - text: "cnpj"
            file: http://cnpj.arturhgq.com/
          - text: "ead"
          - file: http://ead.arturhgq.com/
      - section: "Blog"
        contents:
          - file:  blog.qmd
      - section: "Data"
        contents:
          - file: data.qmd
    page-footer: "Copyright 2022, Artur Quirino" 
    
format:
  html:
    theme:
      light: flatly
    css: styles.css
    toc: true
    linkcolor: "#666699"
    monobackgroundcolor: "#f2f2f2"

execute:
  freeze: auto

comments:
  giscus:
    repo: arturhgq/arturhgq
