on:
  push:
    branches: [main, master]

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          packages:
            arturhgq/read365
            arturhgq/dtools
            arturhgq/ggviz
            any::vroom
            any::data.table
            #any::knitr
            #any::rmarkdown
            #any::downlit
            #any::xml2
            
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x' 
      - run: pip install jupyter
      
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 